const { app, BrowserWindow, dialog, Menu } = require('electron')
const fs = require('node:fs/promises')
const syncFs = require('node:fs')
const { join, resolve } = require('node:path')
const assert = require('node:assert/strict')
const directory = process.env.EDITOR_SMOKE_DIR
app.setPath('userData', join(directory, 'profile'))
let decision = 2 // Cancel (Save All=0, Discard=1)
let savePath
const prompts = []
dialog.showMessageBox = async (_win, options) => { prompts.push(options); return { response: decision } }
dialog.showSaveDialog = async () => ({ canceled: !savePath, filePath: savePath })
const delay = (ms) => new Promise((done) => setTimeout(done, ms))
let win
async function evaluate(source) { return win.webContents.executeJavaScript(source) }
async function until(source) {
  for (let attempt = 0; attempt < 200; attempt++) {
    try { if (await Promise.race([evaluate(source), delay(1000).then(() => false)])) return } catch {}
    await delay(50)
  }
  throw new Error(`Timed out: ${source}`)
}
const timeout = setTimeout(() => { console.error('Smoke test timeout'); app.exit(1) }, 60000)
;(async () => {
  const notes = join(directory, 'notes')
  syncFs.mkdirSync(join(notes, 'nested'), { recursive: true })
  const file = join(notes, 'nested', 'draft.md')
  syncFs.writeFileSync(file, '# Saved\n\nOriginal disk contents.\n')
  require(resolve('out/main/index.js'))
  app.on('will-quit', (event) => event.preventDefault())
  await app.whenReady()
  for (let i = 0; i < 100 && !BrowserWindow.getAllWindows().length; i++) await delay(50)
  win = BrowserWindow.getAllWindows()[0]
  win.webContents.on('console-message', (event) => { if (event.level === 'error') console.error('Renderer:', event.message) })
  await until('window.__store?.getState().sessionReady')
  await evaluate(`window.__store.getState().createProject('Smoke test')`)
  await evaluate(`window.__store.getState().addRootPaths([${JSON.stringify(notes)}])`)
  await evaluate(`window.__store.getState().toggleDir(${JSON.stringify(notes)})`)
  await evaluate(`window.__store.getState().toggleDir(${JSON.stringify(join(notes, 'nested'))})`)
  await evaluate(`window.__store.getState().openFile(${JSON.stringify(file)}, 'draft.md')`)
  await until('document.querySelector(".cm-content")')
  await evaluate(String.raw`(async () => {
    const {liveView} = await import('/src/editor/doc-registry.ts');
    liveView.dispatch({changes:{from:0,to:liveView.state.doc.length,insert:'# Recovered draft\n\nThese unsaved edits must survive.'},selection:{anchor:7}});
  })()`)
  const originalTabId = await evaluate('window.__store.getState().activeTabId')
  const longFile = join(notes, 'long.txt')
  await fs.writeFile(longFile, Array.from({ length: 200 }, (_, i) => `Line ${i + 1}`).join('\n'))
  await evaluate(`window.__store.getState().openFile(${JSON.stringify(longFile)}, 'long.txt')`)
  const longTabId = await evaluate('window.__store.getState().activeTabId')
  await delay(200)
  await evaluate(`document.querySelector('.cm-scroller').scrollTop = 900`)
  await delay(150)
  await evaluate(`window.__store.getState().activateTab(${JSON.stringify(originalTabId)})`)
  // Continuous-typing backup is allowed to fire without an explicit flush call.
  await delay(1400)
  const projectId = await evaluate('window.__store.getState().activeProjectId')
  const sessionFile = join(directory, 'profile', 'sessions', `${projectId}.json`)
  const snapshot = JSON.parse(await fs.readFile(sessionFile, 'utf8'))
  assert.equal(snapshot.tabs[0].draft.content, '# Recovered draft\n\nThese unsaved edits must survive.')
  assert.equal(snapshot.tabs[0].cursor.anchor, 7)
  assert.equal(await fs.readFile(file, 'utf8'), '# Saved\n\nOriginal disk contents.\n')
  console.log('PASS actual editor input is backed up without saving original')
  win.close()
  await delay(300)
  assert.equal(win.isDestroyed(), false)
  assert.ok(prompts.some((p) => p.buttons?.includes('Save All')))
  assert.equal(await evaluate('window.__store.getState().tabs[0].dirty'), true)
  console.log('PASS native window close cancellation preserves unsaved edits')
  // Simulate renderer loss; recovery must read the on-disk draft on reload.
  const crashed = new Promise((done) => win.webContents.once('render-process-gone', done))
  win.webContents.forcefullyCrashRenderer()
  await crashed
  win.webContents.reload()
  await until('window.__store?.getState().sessionReady && window.__store.getState().tabs[0]?.recovered')
  await until('document.querySelector(".cm-content")?.innerText.includes("These unsaved edits must survive.")')
  assert.equal(await evaluate(`!!window.__store.getState().childrenByDir[${JSON.stringify(join(notes, 'nested'))}]`), true)
  await evaluate(`window.__store.getState().activateTab(${JSON.stringify(longTabId)})`)
  await until('document.querySelector(".cm-scroller")?.scrollTop > 500')
  await evaluate(`window.__store.getState().activateTab(${JSON.stringify(originalTabId)})`)
  assert.equal(await evaluate(`import('/src/editor/doc-registry.ts').then(({liveView}) => liveView.state.selection.main.anchor)`), 7)
  console.log('PASS real renderer crash restores draft, selection and nested tree')
  await fs.writeFile(file, '# External version\n\nChanged by another editor.\n')
  await until('window.__store.getState().tabs[0]?.conflict?.type === "changed"')
  await evaluate('window.__store.getState().inspectDiskConflict(window.__store.getState().activeTabId)')
  await until('document.querySelector("[role=dialog]")?.innerText.includes("Overwrite Disk")')
  await delay(500)
  await fs.writeFile('/tmp/full-editor-conflict-smoke.png', (await win.webContents.capturePage()).toPNG())
  assert.ok(await evaluate('document.body.innerText.includes("These unsaved edits must survive.")'))
  console.log('PASS watcher conflict and side-by-side comparison rendered')
  await evaluate('window.__store.getState().resolveDiskConflict(window.__store.getState().activeTabId, "overwrite")')
  assert.equal(await fs.readFile(file, 'utf8'), '# Recovered draft\n\nThese unsaved edits must survive.')
  assert.equal(await evaluate('window.__store.getState().tabs[0].dirty'), false)
  console.log('PASS explicit conflict overwrite saves reviewed content')
  await evaluate(String.raw`(async () => { const {liveView} = await import('/src/editor/doc-registry.ts'); liveView.dispatch({changes:{from:liveView.state.doc.length,insert:'\nAnother draft'}}) })()`)
  await fs.unlink(file)
  await until('window.__store.getState().tabs[0]?.conflict?.type === "missing"')
  savePath = join(directory, 'rescued.md')
  await evaluate('window.__store.getState().saveTabAs(window.__store.getState().activeTabId)')
  assert.ok((await fs.readFile(savePath, 'utf8')).endsWith('Another draft'))
  assert.equal(await evaluate('window.__store.getState().tabs[0].path'), await fs.realpath(savePath))
  console.log('PASS deleted file saved to an explicitly chosen external path')
  // Guarded reload should wait for the latest session before reconstructing tabs.
  const reload = Menu.getApplicationMenu().items.find((item) => item.label === 'View').submenu.items.find((item) => item.label === 'Reload')
  reload.click()
  await delay(300)
  await until('window.__store?.getState().sessionReady && window.__store.getState().tabs[0]?.path.endsWith("rescued.md")')
  console.log('PASS guarded reload restores Save As file and its access grant')
  await evaluate(String.raw`(async () => { const {liveView} = await import('/src/editor/doc-registry.ts'); liveView.dispatch({changes:{from:0,insert:'discard me\n'}}) })()`)
  decision = 1
  const closed = new Promise((done) => win.once('closed', done))
  win.close()
  await closed
  const final = JSON.parse(await fs.readFile(sessionFile, 'utf8'))
  assert.equal(final.tabs[0].draft, undefined)
  assert.equal((await fs.readFile(savePath, 'utf8')).startsWith('discard me'), false)
  console.log('PASS discard-and-close clears recovery draft without modifying disk')
  clearTimeout(timeout)
  app.exit(0)
})().catch((error) => { console.error(error); clearTimeout(timeout); app.exit(1) })
